# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pln < Formula
  desc "Mesh network daemon"
  homepage ""
  version "0.1.0-alpha.122"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.122/pln_0.1.0-alpha.122_darwin_amd64.tar.gz"
      sha256 "0b6ffba27e7c915e8d699c278cee2cb8afbeb07a85eba23945954c140ae525d1"

      define_method(:install) do
        bin.install "pln"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.122/pln_0.1.0-alpha.122_darwin_arm64.tar.gz"
      sha256 "ac0f540293d7a4d7a21adb995c05fa6750b98e0c49acef2ba0926fa4560536fa"

      define_method(:install) do
        bin.install "pln"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.122/pln_0.1.0-alpha.122_linux_amd64.tar.gz"
      sha256 "cd172b6f54d6beeaee111767a2ab4a17e420f1445ee1309452bf5d0c7efaf24f"
      define_method(:install) do
        bin.install "pln"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.122/pln_0.1.0-alpha.122_linux_arm64.tar.gz"
      sha256 "31cd47c90ccdc95a97158d724b2cfbfbb43c3361a5924aa1628e45b98a73fccb"
      define_method(:install) do
        bin.install "pln"
      end
    end
  end

  service do
    run [opt_bin/"pln", "up"]
    keep_alive true
    log_path var/"log/pln.log"
    error_log_path var/"log/pln.log"
  end
end
