# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pln < Formula
  desc "Mesh network daemon"
  homepage ""
  version "0.1.0-alpha.38"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.38/pln_0.1.0-alpha.38_darwin_amd64.tar.gz"
      sha256 "6dabad02e3eb83e17b8a4f402f79cb2d2623fb1bb6bf101e7df3fd9f13b20621"

      define_method(:install) do
        bin.install "pln"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.38/pln_0.1.0-alpha.38_darwin_arm64.tar.gz"
      sha256 "beb0c3da43547abd79228f9c3ad4563f8d84cca04322cfb333992c6e568961ea"

      define_method(:install) do
        bin.install "pln"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.38/pln_0.1.0-alpha.38_linux_amd64.tar.gz"
      sha256 "f517e5acfc6e70dde8e4e4fd97d6af3947ebfa58509bd54fb8883622bf39a4a5"
      define_method(:install) do
        bin.install "pln"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sambigeara/pollen/releases/download/v0.1.0-alpha.38/pln_0.1.0-alpha.38_linux_arm64.tar.gz"
      sha256 "07b6aad99f233e7f5e8659b78e003397183a0c7a726f730536e8db08236d8f38"
      define_method(:install) do
        bin.install "pln"
      end
    end
  end

  service do
    run [opt_bin/"pln", "up"]
    keep_alive true
    log_path var/"log/pln.log"
    error_log_path var/"log/pln.log"
  end
end
